[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
crowdfunding = "7zT6hzi2QoHtZrhsBqoapB5nEX94SBvoX21awsELDdGx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
